spring:
  application:
    name: spring-outbox-consumer-example
  data:
    redis:
      port: 6379
      host: outbox-consumer-redis
server:
  port: 8080
logging:
  level:
    io.github.dmitriyiliyov.springoutbox: debug
outbox:
  thread-pool-size: 2
  publisher:
    enabled: false
  consumer:
    enabled: true
    clean-up:
      enabled: true
      ttl: 10m
    cache:
      enabled: true
      cache-name: "outbox:consumed"
    metrics:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true