oncebox:
  publisher:
    sender:
      type: kafka
    events:
      create-order:
        topic: orders.created
        batch-size: 200
        polling:
          min-fixed-delay: 200ms
      update-order:
        topic: orders
        batch-size: 200
        polling:
          min-fixed-delay: 500ms
      delete-order:
        topic: orders
        batch-size: 200
        polling:
          min-fixed-delay: 1s