spring:
  application:
    name: spring-outbox-producer-example
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        generate_statistics: true
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    baseline-on-migrate: true
logging:
  level:
    root: info
outbox:
  thread-pool-size: 7
  tables:
    auto-create: true
  publisher:
    defaults:
      batch-size: 100
      initial-delay: 30s
      max-retries: 3
      backoff:
        delay: 1m
        multiplier: 1.5
    clean-up:
      enabled: true
      batch-size: 500
      ttl: 10m
      initial-delay: 2m
      fixed-delay: 500ms
    stuck-recovery:
      batch-size: 500
      initial-delay: 2m
      fixed-delay: 5s
    dlq:
      enabled: true
      batch-size: 200
      transfer-to-initial-delay: 2m
      transfer-to-fixed-delay: 1m
      transfer-from-initial-delay: 2m
      transfer-from-fixed-delay: 10m
      metrics:
        gauge:
          enabled: true
          cache:
            ttls: [60s, 60s, 60s]
    metrics:
      enabled: true
      gauge:
        enabled: true
        cache:
          ttls: [60s, 60s, 60s]
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true