outbox:
  publisher:
    sender:
      type: rabbit
    events:
      create-order:
        topic: orders-exchange
        batch-size: 200
        polling:
          min-fixed-delay: 200ms
      update-order:
        topic: orders-exchange
        batch-size: 200
        polling:
          min-fixed-delay: 500ms
      delete-order:
        topic: orders-exchange
        batch-size: 200
        polling:
          min-fixed-delay: 1s