name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-and-ut-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Built test utils
        working-directory: ./spring-outbox-tests/spring-outbox-test-utils
        run: mvn clean install -Dgpg.skip=true

      - name: Build + UT + IT
        run: mvn -B clean install -Dgpg.skip=true

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .
          retention-days: 1

      - name: Upload local Maven repo
        uses: actions/upload-artifact@v4
        with:
          name: maven-repo
          path: ~/.m2/repository/io/github/dmitriy-iliyov
          retention-days: 1

  infra-outbox-it:
    runs-on: ubuntu-latest
    needs: build-and-ut-it
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Download local Maven repo
        uses: actions/download-artifact@v4
        with:
          name: maven-repo
          path: ~/.m2/repository/io/github/dmitriy-iliyov

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run infra OUTBOX IT
        working-directory: ./spring-outbox-tests/spring-outbox-integration-tests
        run: mvn -B verify -Dgpg.skip=true -Dgroups=outbox -Dspring.profiles.active=outbox -Ddb=postgres

  kafka-infra-inbox-it:
    runs-on: ubuntu-latest
    needs: build-and-ut-it

    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Download local Maven repo
        uses: actions/download-artifact@v4
        with:
          name: maven-repo
          path: ~/.m2/repository/io/github/dmitriy-iliyov

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run infra INBOX IT
        working-directory: ./spring-outbox-tests/spring-outbox-integration-tests
        run: mvn -B verify -Dgpg.skip=true -Dgroups=kafka-inbox -Dspring.profiles.active=inbox,kafka -Ddb=postgres

  rabbit-infra-inbox-it:
    runs-on: ubuntu-latest
    needs: build-and-ut-it

    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Download local Maven repo
        uses: actions/download-artifact@v4
        with:
          name: maven-repo
          path: ~/.m2/repository/io/github/dmitriy-iliyov

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run infra INBOX IT
        working-directory: ./spring-outbox-tests/spring-outbox-integration-tests
        run: mvn -B verify -Dgpg.skip=true -Dgroups=rabbit-inbox -Dspring.profiles.active=inbox,rabbit -Ddb=postgres