name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and run UT and IT
        run: mvn clean verify -X -Dgpg.skip=true

      - name: Build and run E2ET
        run: mvn -f spring-outbox-tests/spring-outbox-e2e-tests/pom.xml clean verify -X -Dgpg.skip=true

      - name: Upload coverage to Codecov
        if: github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/target/site/jacoco/jacoco.xml"
          fail_ci_if_error: true
