name: E2E

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build
        run: mvn clean install -DskipTests -Dgpg.skip=true

      - name: Build and run E2E
        run: mvn -f spring-outbox-tests/spring-outbox-e2e-tests/pom.xml clean verify -X -Dgpg.skip=true
